name: C/C++ CI

on:
  push:
    branches: [ main, "dev/**"  ]
  pull_request:
    branches: [ main, "dev/**"  ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive # Ensures that submodules are also checked out

    - name: Static analysis
      run: find . -name '*.c' | xargs clang-tidy --quiet
    
    - name: Generate coverage report
      run: make coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Run make to build project
      run: make
